Fri_Ends/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('submission/',include('Submission.urls')),
    path('assignment/',include('Assignment.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Submission/urls.py
from django.urls import path
from . import views

app_name = 'Submission'

urlpatterns = [
    path('<int:submission_pk>/coaching/<int:coaching_pk>/like/', views.like_coaching, name="like_coaching"),
    path('<int:submission_pk>/coaching/', views.create_coaching, name="create_coaching"),
    path('<int:pk>/fail/', views.fail, name="fail"),
    path('<int:pk>/success/', views.success, name="success"),
    path('<int:pk>/', views.detail, name="detail"),
]

Submission/models.py
from django.db import models
from django.conf import settings

# Create your models here.
from Assignment.models import Assignment

def submission_image_path(instance, filename):
    return f'submission/{filename}'

class Submission(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = submission_image_path, null=True)
    status = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.pk}] {self.title}'

class Coaching(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_coachings', blank=True)
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'[{self.submission.title} - {self.pk}] {self.content}'

Submission/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .models import Submission, Coaching

def detail(request, pk):
    submission =  get_object_or_404(Submission, pk=pk)
    content = {
        'submission' : submission,
        'coachings' : submission.coaching_set.all()
    }
    return render(request, 'Submission/detail.html', content)

@login_required
def success(request, pk):
    submission =  get_object_or_404(Submission, pk=pk)
    user = request.user
    if request.method == 'POST':
        if user.id == submission.assignment.created_user.id:
            profile = submission.writer.profile
            profile.points += 1
            submission.status = 'succeed'
            profile.save()
            submission.save()
    return redirect('Submission:detail', pk)

@login_required
def fail(request, pk):
    submission =  get_object_or_404(Submission, pk=pk)
    user = request.user
    if request.method == 'POST':
        if user.id == submission.assignment.created_user.id:
            submission.status = 'failed'
            submission.save()
    return redirect('Submission:detail', pk)

@login_required
def create_coaching(request, submission_pk):
    submission = get_object_or_404(Submission, pk=submission_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        writer = request.user
        coaching = Coaching(content=content, submission=submission, writer=writer)
        coaching.save()
    return redirect('Submission:detail', submission_pk)

@login_required
def like_coaching(request, submission_pk, coaching_pk):
    coaching = get_object_or_404(Coaching, pk=coaching_pk)
    user = request.user
    if coaching.like_users.filter(pk=user.pk).exists():
        coaching.like_users.remove(user)
    else:
        coaching.like_users.add(user)
    return redirect('Submission:detail', submission_pk)

Submission/templates/Submission/detail.html
{% extends 'Assignment/base.html' %}

{% block body %}
<div class="single-product-area mt-50">
    <h1>{{ submission.assignment.title }}<small class="text-muted">의 제출물 목록</small></h1>
    <hr>

    <!-- 제출물 내용 -->
    <div>
        <h2>제목 : {{ submission.title }}</h2>
        <p>내용 : {{ submission.content }}</p>
        <p>
            상태 :
            {% if submission.status == 'requested' %}
            미검수
            {% elif submission.status == 'succeed' %}
            성공
            {% elif submission.status == 'failed' %}
            실패
            {% endif %}
        </p>
        {% if submission.image %}
        <img src="{{ submission.image.url }}" alt="{{ submission.image }}"></img>
        {% endif %}
        <p>작성시각 : {{ submission.created_at }}</p>
        <p>마지막 수정 시각 : {{ submission.updated_at }}</p>
    </div>
    <hr>

    <!-- 검수 -->
    {% if user.id == submission.assignment.created_user.id %}
        {% if submission.status == 'requested' %}
            <div>
                <form action="{% url 'Submission:success' submission.pk %}" style="display: inline" method='POST'>
                    {% csrf_token %}
                    <input type="submit" class="btn btn-success" value="Success"/>
                </form>
                <form action="{% url 'Submission:fail' submission.pk %}" style="display: inline" method='POST'>
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Fail"/>
                </form>
            </div>
        <hr>
        {% endif %}
    {% endif %}

    <!-- 댓글창 -->
    <div>
        <form action="{% url 'Submission:create_coaching' submission.pk %}" method='POST'>
            {% csrf_token %}
            댓글 달기 : <input type="text" name="content"/>
            <input type="submit" value="Submit"/>
        </form>
        <div>
            {% for coaching in coachings %}
            <div class="mt-15">
                <span class="lead">{{ coaching.content }}</span>
                <a href="{% url 'Submission:like_coaching' submission.pk coaching.pk %}" class="card-link">
                    {% if user in coaching.like_users.all %}
                        <i class='fas fa-heart fa-lg' style='color:crimson'></i>
                    {% else %}
                        <i class='far fa-heart fa-lg' style='color:black'></i>
                    {% endif %}
                </a>
                <span>{{ coaching.like_users.count }}</span>
                <div class="blockquote-footer">
                    <span class="mr-15">{{ coaching.writer.username }}</span>
                    <small class="text-muted">{{ coaching.created_at }}</small>
                </div>
            </div>
            {% empty %}
            <br>
            <span>아직 아무도 훈수를 두지 않았습니다. 훈수를 통해 피드백을 주세요!</span>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}