Assignment/urls.py
from django.urls import path
from . import views

app_name = 'Assignment'

urlpatterns = [
    path('<int:pk>/submit/',views.submit,name="submit"),
    path('<int:pk>/',views.detail,name="detail"),
    path('new/',views.new,name="new"),
    path('',views.index,name="index"),
    ]

Fri_Ends/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('submission/',include('Submission.urls')),
    path('assignment/',include('Assignment.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Submission/urls.py
from django.urls import path
from . import views

app_name = 'Submission'

urlpatterns = [
    path('<int:submission_pk>/coaching/<int:coaching_pk>/like/', views.like_coaching, name="like_coaching"),
    path('<int:submission_pk>/coaching/', views.create_coaching, name="create_coaching"),
    path('<int:pk>/fail/', views.fail, name="fail"),
    path('<int:pk>/success/', views.success, name="success"),
    path('<int:pk>/', views.detail, name="detail"),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('change_password/', views.change_password , name = 'change_password'),    
    path('edit/', views.edit , name = 'edit'),    
    path('delete/', views.delete , name = 'delete'),    
    path('logout/', views.logout , name = 'logout'),    
    path('login/', views.login , name = 'login'),    
    path('signup/', views.signup , name = 'signup'),    
    path('profile/', views.pro_file , name = 'profile'),    
]

Assignment/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Assignment(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    photo = models.ImageField(blank=True)
    pay_coin = models.IntegerField(default = 0)
    status = models.BooleanField(default=True)
    created_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    end_at = models.DateTimeField()
    updated_at = models.DateTimeField(auto_now=True)

class AssignmentUser(models.Model):
    assignment = models.ForeignKey(Assignment,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

Assignment/forms.py
from django import forms
from .models import Assignment
from Submission.models import Submission
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit,Layout

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['title','content','photo','end_at',]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit','작성합시다.'))

class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ['title', 'content', 'image',]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit','제출.'))

Assignment/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Assignment,AssignmentUser
from .forms import AssignmentForm, SubmissionForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    assignment = Assignment.objects.all().order_by('-id')
    return render(request,'Assignment/index.html',{'assignment':assignment})

@login_required
def new(request):
    if(request.method == 'POST'):
        form = AssignmentForm(request.POST,request.FILES)
        if form.is_valid():
            user = request.user
            point = user.profile.points
            if (point != 0):
                points = point -1
                user.profile.points = points
                user.profile.save()
                assignment = form.save(commit=False)
                assignment.created_user = request.user
                assignment.save()
                return redirect('Assignment:detail',assignment.pk)
            else:
                messages.info(request, '포인트가 없습니다.')
                return redirect('Assignment:index')
        return redirect('Assignment:index')
    else:
        form = AssignmentForm()
    return render(request,'Assignment/form.html',{'form':form})

def detail(request,pk):
    assignment = get_object_or_404(Assignment, pk=pk)
    assignmentUsers = AssignmentUser.objects.filter(assignment=pk)
    checkAs = AssignmentUser.objects.filter(assignment=pk,user=request.user.pk)
    if (request.method == 'POST'):
        if(checkAs.exists()):
            messages.info(request, '이미 과제를 참여했습니다.')
            return redirect('Assignment:detail',assignment.pk)
        assignmentUser = AssignmentUser()
        assignmentUser.assignment = assignment
        assignmentUser.user = request.user
        assignmentUser.save()
        messages.info(request, '과제 참여완료')
        return redirect('Assignment:detail',assignment.pk)
    else:
        return render(request,'Assignment/detail.html',{
            'assignment':assignment,
            'count':assignmentUsers.count(),
            'checkAs': checkAs,
            'submissions': assignment.submission_set.all()
        })

@login_required
def submit(request, pk):
    assignment = get_object_or_404(Assignment, pk=pk)
    if (request.method == 'POST'):
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.writer = request.user
            submission.assignment = assignment
            submission.status = 'requested'
            submission.save()
            return redirect('Assignment:detail', assignment.pk)
        else:
            messages.info(request, '제출 실패')
            return redirect('Assignment:detail', assignment.pk)
    else:
        form = SubmissionForm()
    return render(request, 'Assignment/submit.html', {'form':form})

Assignment/templates/Assignment/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fri_End</title>
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
    {% block css %} {% endblock %}
</head>
<body>
<!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}" charset="UTF-8"></script>
<div class="main-content-wrapper d-flex clearfix">
        <!-- Nav -->
        {% include 'Assignment/base_nav.html' %}
        <!-- endNav-->
        <!-- Contents -->
        {% block body %}
        {% endblock %}
        <!-- endContents -->
    </div>

    <!-- Footer -->
    {% include 'Assignment/base_footer.html' %}


    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>

</body>

</html>

Assignment/templates/Assignment/base_footer.html
<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">
    <div class="container">
        <div class="row align-items-center">
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">
                    <!-- Logo -->
                    <div class="footer-logo mr-50">
                        <a href="index.html"><img src="img/core-img/logo2.png" alt=""></a>
                    </div>
                    <!-- Copywrite Text -->
                    <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-lg-8">
                <div class="single_widget_area">
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="index.html">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="shop.html">Shop</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="product-details.html">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="cart.html">Cart</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="checkout.html">Checkout</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

Assignment/templates/Assignment/base_nav.html
{% load staticfiles %}
<!-- Mobile Nav (max width 767px)-->
<div class="mobile-nav">
    <!-- Navbar Brand -->
    <div class="amado-navbar-brand">
        <a href="index.html"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
    </div>
    <!-- Navbar Toggler -->
    <div class="amado-navbar-toggler">
        <span></span><span></span><span></span>
    </div>
</div>

<!-- Header Area Start -->
<header class="header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <a href="{% url 'Assignment:index' %}"><img src="{% static 'img/core-img/friend.png' %}" alt=""></a>
    </div>
    <!-- Amado Nav -->
    <nav class="amado-nav">
        <ul>
            <li class="active"><a href="{% url 'Assignment:index' %}">Home</a></li>
            <li><a href="{% url 'Assignment:new' %}">과제등록</a></li>
        </ul>
    </nav>
    <!-- Button Group -->
    <div class="amado-btn-group mt-30 mb-100">
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:profile'%}" class="btn amado-btn mb-15"> {{user.username}}</a>
        <form action = '{% url 'accounts:logout'%}' method = 'POST' style = 'display:inline;'>
        {%csrf_token%}
            <input type="submit" class="btn amado-btn mb-15" value="Log out"/>
        </form>
        {% else%}
            <a href="{% url 'accounts:login'%}" class="btn amado-btn mb-15"> Sign in</a>
            <a href="{% url 'accounts:signup'%}" class="btn amado-btn mb-15"> Sign up</a>

        {% endif %}
    </div>
    <!-- Cart Menu -->
    <div class="cart-fav-search mb-100">

        <a href="#" class="fav-nav"><img src="{% static 'img/core-img/favorites.png' %}" alt=""> Point Shop</a>
        <a href="#" class="search-nav"><img src="{% static 'img/core-img/search.png' %}" alt=""> Search</a>
    </div>
    <!-- Social Button -->
    <div class="social-info d-flex justify-content-between">
        <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    </div>
</header>
<!-- Header Area End -->

Assignment/templates/Assignment/detail.html
 {% extends 'Assignment/base.html' %}

{% block body %}
<div class="single-product-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-lg-7">
                <div class="single_product_thumb" style="margin-bottom:0">
                    <div class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <a class="gallery_img" href="/media/{{ assignment.photo }}">
                                    <img class="d-block w-100" src="/media/{{ assignment.photo }}" onerror="this.src='/static/img/bg-img/no_detail_img.gif'" alt="First slide" style="width: 573px; height: 592px;">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-5">
                <div class="single_product_desc">
                    <!-- Product Meta Data -->
                    <div class="product-meta-data">
                        <div class="line"></div>
                        <p class="product-price">마감일 : {{assignment.end_at}}</p>
                        <h3>{{assignment.title}}</h3>
                        <p class="avaibility"><i class="fa fa-circle"></i> 과제 참여자: {{count}}</p>
                    </div>
                    <div class="short_overview my-5">
                        <p>
                            {{assignment.content}}
                        </p>
                    </div>
                    {% if checkAs %}
                        <a href="{% url 'Assignment:submit' assignment.pk %}" class="btn btn-primary">과제 제출</a>
                    {% else %}
                    <form class="cart clearfix" method="post">
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                        <button type="submit" class="btn amado-btn">과제 신청</button>
                        {% endif %}
                    </form>
                    {% endif %}
                </div>
            </div>

            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">제목</th>
                  <th scope="col">작성자</th>
                  <th scope="col">상태</th>
                  <th scope="col">제출일자</th>
                </tr>
              </thead>
              <tbody>
                {% for submission in submissions %}
                <tr>
                  <th scope="row">{{submission.id}}</th>
                  <td><a href="{% url 'Submission:detail' submission.pk %}">{{submission.title}}</a></td>
                  <td>{{submission.writer.username}}</td>
                  <td>
                    {% if submission.status == 'requested' %}
                    미검수
                    {% elif submission.status == 'succeed' %}
                    성공
                    {% elif submission.status == 'failed' %}
                    실패
                    {% endif %}
                  </td>
                  <td>{{submission.created_at}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>


        </div>
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        <script>
            alert('{{ message }}');
        </script>
    {% endfor %}
{% endif %}

{% endblock %}

Assignment/templates/Assignment/form.html
 {% extends 'Assignment/base.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="single-product-area mt-50">
    <h1>과제 등록</h1>
    {% crispy form %}
</div>
<script>
    $(function(){
        $('.datetimeinput').datepicker({
            format: 'mm/dd/yyyy',
            startDate: '-3d'
        });
    })
</script>
{% endblock %}

Assignment/templates/Assignment/index.html
{% extends 'Assignment/base.html' %}

{% block body %}
<div class="products-catagories-area clearfix">
    <div class="amado-pro-catagory clearfix">
        {% for item in assignment %}
            <div class="single-products-catagory clearfix">
                <a href="{{item.pk}}">
                    <img src="/media/{{ item.photo }}" alt="이미지없음" onerror="this.src='/static/img/bg-img/no_detail_img.gif'" style="width: 368px; height: 368px;">
                    <!-- Hover Content -->
                    <div class="hover-content">
                        <div class="line"></div>
                        <p>마감일 {{item.end_at}}</p>
                        <h4>{{item.title}}</h4>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% if messages %}
    {% for message in messages %}
        <script>
            alert('{{ message }}');
        </script>
    {% endfor %}
{% endif %}
{% endblock %}

Assignment/templates/Assignment/submit.html
 {% extends 'Assignment/base.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="single-product-area mt-50">
    <h1>과제 제출</h1>
    {% crispy form %}
</div>
{% endblock %}