Assignment/urls.py
from django.urls import path
from . import views

app_name = 'Assignment'

urlpatterns = [
    path('<int:pk>/submit/',views.submit,name="submit"),
    path('<int:pk>/',views.detail,name="detail"),
    path('new/',views.new,name="new"),
    path('',views.index,name="index"),
    ]

Fri_Ends/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('submission/',include('Submission.urls')),
    path('assignment/',include('Assignment.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('change_password/', views.change_password , name = 'change_password'),    
    path('edit/', views.edit , name = 'edit'),    
    path('delete/', views.delete , name = 'delete'),    
    path('logout/', views.logout , name = 'logout'),    
    path('login/', views.login , name = 'login'),    
    path('signup/', views.signup , name = 'signup'),    
    path('profile/', views.pro_file , name = 'profile'),    
]

accounts/models.py
from django.db import models
from django.conf import settings
# form.profile.user
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    points = models.IntegerField(default=3)
    
    def __str__(self):
        return f'{self.user}님 - 포인트는  : {self.points} '

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email','first_name','last_name',)
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm , UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import UserCustomChangeForm
from .models import Profile


def signup(request):
    if request.user.is_authenticated:
        return redirect("Assignment:index")
        
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        
        
        if form.is_valid():
            user = form.save()
            
            profile = Profile(user=user)
            profile.save()
            
            auth_login(request, user, backend='allauth.account.auth_backends.AuthenticationBackend')
            return redirect('Assignment:index')
    else :
        form = UserCreationForm()
    return render(request,'accounts/auth_form.html',{'form':form})

def login(request):
    
    if request.user.is_authenticated:
        return redirect("Assignment:index")
        
    if request.method == "POST":
        form = AuthenticationForm(request , request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('Assignment:index')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})
    
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('Assignment:index')
    return redirect('Assignment:index')
    
def delete(request):
    if request.method=='POST':
        request.user.delete()
        
    return redirect('Assignment:index')

def edit(request):
    if request.method == 'POST':
        form = UserCustomChangeForm(request.POST,instance = request.user)
        if form.is_valid:
            form.save()
            return redirect('Assignment:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
    return render(request,'accounts/auth_form.html',{'form':form})
    
def change_password(request):
    if request.method =='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request,user)
            return redirect('AssertionError:index')
    else:
        form = PasswordChangeForm(request.user)
    return render(request,'accounts/auth_form.html',{'form':form})
    
def pro_file(request):
    user = request.user
    assignments = user.assignment_set.all()
    # submissions = user.submission_set.all()
    return render(request,'accounts/profile.html', {'assignments': assignments})

accounts/templates/accounts/auth_form.html
{% extends 'Assignment/base.html' %}
{% block body%}
{%load crispy_forms_tags %}
<div class='single-product-area mt-50'>
{%if request.resolver_match.url_name == 'signup'%}
<h1 class = 'text-center'>회원가입</h1>
{%elif request.resolver_match.url_name == 'edit'%}
<h1 class = 'text-center'>회원 정보 수정</h1>
{%elif request.resolver_match.url_name == 'change_password'%}
<h1 class = 'text-center'>비밀번호 변경</h1>
{%else%}
<h1 class = 'text-center'>로그인</h1>
{%endif%}

<form action = '' method = "POST">
    {% csrf_token%}
    {{ form|crispy }}
    
    <input type="submit" value="Submit"/>
</form>

</div>

{%endblock%}

accounts/templates/accounts/login.html
{%extends 'Assignment/base.html' %}
{%block body%}
{% load bootstrap4%}
{% load socialaccount%}
<div class="container single-product-area mt-100">
    
    <h1 class = 'text-center'> 로그인</h1>
<form action='' method = 'POST'>
    {%csrf_token%}
    {% bootstrap_form form %}
    {% buttons%}
        <hr>
        <button type = 'submit' class = 'container  mt-10 btn btn-warning'>
            로그인
        </button>
        <hr>
        <button type = 'submit' class = 'container mt-10 btn btn-warning'>
            취소
        </button>
    {%endbuttons%}
</form>
<hr>
<a href = "{% provider_login_url 'kakao' method = 'outh2' %}" class = 'container mt-10 btn btn-warning'> KaKao Login</a>
    
</div>


{% endblock%}

accounts/templates/accounts/profile.html
{% extends 'Assignment/base.html' %}
{% block body%}

<div class="single-product-area mt-50">
<p class = 'text-center'>{{user.profile}}</p>
        <h2 class = 'text-center'>과제 등록란</h2>
        {% for assignment in assignments %}
            <p class = 'text-center'>{{assignment.id}} <a href='{% url 'Assignment:detail' assignment.pk%}'> 제목 : {{assignment.title}}</a></p>
            
        {%endfor%}
        <!--<h2>과제 참여란</h2>-->
        <!--{% for submission in submissions %}-->
        <!--    <p>글 번호 : {{submission.id}}제목 : {{submission.title}}</p>-->
            
        <!--{%endfor%}-->
        
<a href="{% url 'accounts:edit'%}" class="container  mt-10 btn amado-btn mb-15"> 회원정보 수정</a>
<hr>
<a href="{% url 'accounts:change_password'%}" class="container  mt-10 btn amado-btn mb-15"> 비밀번호 변경</a>
<hr>
<form action = '{% url 'accounts:delete'%}' method = 'POST' style = 'display:inline;'>
        {%csrf_token%}
            <input type="submit" class="container  mt-10 btn amado-btn mb-15" value="회원 탈퇴"/>
        </form>

</div>
{%endblock%}